### ISSUE TITLE
Has no effect

### ISSUE THREAD

**Issue by Keith94** [quinton-ashley/firefox-hide-scrollbars#1]
The add-on doesn't seem to do anything for me. I'm running Nightly 62.

**Comment by quinton-ashley** [comment]
That's strange.  It doesn't take away the scrollbars or can you not scroll?  It only doesn't work for me on sites like Gmail in which interior divs are scrollable but the body of the HTML is not.  I'll try to fix this soon.

**Comment by Keith94** [comment]
It didn't take away scroll bars for me, and I could still scroll. Sorry that I couldn' provide more info than that!

**Comment by qoheniac** [comment]
It works for me (Firefox 60.0.1) on most sites. Good work, thank you!

**Comment by quinton-ashley** [comment]
@Keith94 What OS are you using?

**Comment by Keith94** [comment]
>Name 	Firefox
Version 	62.0a1
Build ID 	20180531101452
Update History 	
Update Channel 	nightly
User Agent 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0
OS 	Windows_NT 10.0

**Comment by quinton-ashley** [comment]
I've only tested it on macOS and Windows 10 using the Developer Edition but not the nightly build.  Can't imagine why it wouldn't work on the nightly build though.  Try removing the extension and adding it to firefox again because I just put out a new version that requires additional permissions.

**Comment by Keith94** [comment]
I tested in a fresh profile. It literally has no effect for me.

![2018-06-01_20-43-58](https://user-images.githubusercontent.com/5490615/40870092-9a5d9e1a-65dc-11e8-8fe3-923f8c7f1f8e.gif)

**Comment by Keith94** [comment]
Oh. AMO doesn't offer the latest 1.0.3. So I didn't test that one yet.

**Comment by quinton-ashley** [comment]
Thanks for the quick response and the gif!  1.0.2 is the latest right now, 1.0.3 was just an edit to the userscript version sorry for the confusion.  That indeed looks like it really doesn't work, I'll check it out on the nightly version.  Do you have a Firefox account?

**Comment by Keith94** [comment]
I do

**Comment by Keith94** [comment]
Can you link me the userscript version?

**Comment by quinton-ashley** [comment]
Just made a quick update that makes the extension work on the nightly build!  1.0.4 is up on AMO now.  The userscript version is in the repo and on [Greasyfork](https://greasyfork.org/en/scripts/368573-firefox-hide-scrollbars), it'll autoupdate from this repo.

**Comment by Keith94** [comment]
Thanks! I can confirm it's fixed
