### ISSUE TITLE
Known Issue: Youtube Play Position glitch

### ISSUE THREAD

**Issue by quinton-ashley** [quinton-ashley/firefox-hide-scrollbars#11]
Hey @hensm sorry to bother you again but I noticed some odd behavior on Youtube.  If I click anywhere on the video timeline to skip ahead my mouse gets stuck dragging the play position.  When I toggle off the extension and reload the page it's back to normal.  Any ideas on what might be causing that?

**Comment by hensm** [comment]
#12 

Just a really dumb mistake as it turns out.

There was a `mousemove` listener set on `mousedown` over the progress bar that wasn't being removed on `mouseup`. Or something like that.

**Comment by quinton-ashley** [comment]
Ah weird.  Thanks!
