### ISSUE TITLE
Element placement issues with articles on The Guardian

### ISSUE THREAD

**Issue by quinton-ashley** [quinton-ashley/firefox-hide-scrollbars#14]
@hensm check out an article on [The Gaurdian](https://www.theguardian.com).  For some reason the footer is placed just below the screen and then the rest of the articles is covered.  Also on this article on the [Washington Post](https://www.washingtonpost.com/graphics/2018/lifestyle/science-behind-improv-performance/?noredirect=on&utm_source=reddit.com&utm_term=.55a961ab494c) there is a lot of horizontal scroll-able areas but without the extension they don't scroll horizontally.

**Comment by hensm** [comment]
That happens because it sets the article height at 100% of `<body>`, which is usually the whole content height.

I think I may have found a better way to handle these problems. Instead of messing with `<body>`, we can just move it into a separate wrapper element.

I'll experiment with that later.

**Comment by quinton-ashley** [comment]
I've added blacklisting sites to the goals in the Donation section of the readme
