### ISSUE TITLE
Add-on prevents canvas game from working

### ISSUE THREAD

**Issue by qoheniac** [quinton-ashley/firefox-hide-scrollbars#15]
On [this](https://www.zeit.de/sport/2018-06/fussball-wm-torschuss-wo-ging-er-rein) site there is a little canvas game that only works if I deactivate the add-on. Try to click on "Okay!" (nothing will happen) and then once again after showing the scrollbars and reloading the page. (Tested with Firefox 60.0.2 on Fedora 28)

**Comment by quinton-ashley** [comment]
I've added blacklisting sites to the goals in the Donation section of the readme
