### ISSUE TITLE
Incompatible with Vim Vixen

### ISSUE THREAD

**Issue by oblitum** [quinton-ashley/firefox-hide-scrollbars#18]
Hi, this is a great plugin, but sadly it causes [Vim Vixen](https://github.com/ueokande/vim-vixen) not to work. Vim Vixen provides Vim-like keybindings to Firefox, but those won't work when hide-scrollbars is enabled (like `gg` to scroll to the top).

**Comment by quinton-ashley** [comment]
You can use the normal shortcut, holding `shift + spacebar`, to scroll to the top of the page.  Sorry it's incompatible with Vim Vixen.
