### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by happysurf** [quinton-ashley/firefox-hide-scrollbars#20]
The **Netvibes** web pages doesn't scroll if hide-scrollbars is enabled.
The extension **Scroll Progress New** at https://addons.mozilla.org/en-US/firefox/addon/scroll-progress-new/ is broken if hide-scrollbars is enabled.

**Comment by quinton-ashley** [comment]
hide scrollbars doesn't work with any other scroll related extensions sorry.  It will not work on some sites either so disable it on those sites.

I've added blacklisting sites to the goals in the Donation section of the readme
