### ISSUE TITLE
Hide-Scrollbars Causes Youtube Page to Scroll Up 

### ISSUE THREAD

**Issue by koolx** [quinton-ashley/firefox-hide-scrollbars#22]
Hide-Scrollbars is causing issues with youtube. When I click to edit my comment in the comment section the page moves up. Please fix.

**Comment by quinton-ashley** [comment]
I can't replicate this behavior sorry, it works fine for me.  Do you have any other extensions that would affect youtube?

**Comment by quinton-ashley** [comment]
fixed in v3.0.0
