### ISSUE TITLE
Bottom of Pages Cut Off

### ISSUE THREAD

**Issue by McCovican** [quinton-ashley/firefox-hide-scrollbars#23]
I'm having an issue where the bottom of pages are being cut off with this extension (seems about 10px or so). 

Addon disabled: ![disabled](https://x.brutix.uk/401473.png)

Addon enabled: ![enabled](https://x.brutix.uk/7d9004.png)

Obviously it's a minor cutoff, and has little consequence in this example, but there are sites where I struggle to get at a link that's sitting right on the bottom of a page because of this.

Edit: Actually, this extension has *so many* completely game-breaking bugs, but hasn't been updated properly in years so RIP I guess.

Edit: This extension is now entirely obsolete. Everything can be achieved (without any negative side-effects or entirely breaking websites, as this addon does) by simply using the moz CSS:

`* {
    scrollbar-width: none !important;
}`

**Comment by quinton-ashley** [comment]
Thank you for your update on this!  The extension did have a lot of problems on some sites that I think couldn't be fixed using the previous methods.  I just updated the extension to use the new moz CSS!
