### ISSUE TITLE
Scrollbars sometimes come up

### ISSUE THREAD

**Issue by paniash** [quinton-ashley/firefox-hide-scrollbars#29]
I'm not sure how this can be reproducible but every once in a while, when starting firefox, the scrollbars seem to become visible. I then have to remove and install the addon for it to work again.

**Comment by quinton-ashley** [comment]
huh that's strange, try turning it on and off instead if that happens again

**Comment by paniash** [comment]
Yeah, I do that whenever it happens, but gets quite annoying at times.

**Comment by paniash** [comment]
Never mind, I found a direct fix in `about:config` :-)

**Comment by quinton-ashley** [comment]
what was the fix?

**Comment by paniash** [comment]
> what was the fix?

Set the option `widget.non-native-theme.scrollbar.size` in `about:config` to 0.

**Comment by quinton-ashley** [comment]
Neat! So you don't have to use the extension anymore?

**Comment by paniash** [comment]
> Neat! So you don't have to use the extension anymore? 

So far, that seems to be the case! However, thanks for your plugin before this problem. Not sure what it was but the plugin did help me a lot before!
