### ISSUE TITLE
Scrolling via keys and touch pad not working

### ISSUE THREAD

**Issue by qoheniac** [quinton-ashley/firefox-hide-scrollbars#4]
On a lot of pages (all?) scrolling via up and down keys isn't working and on some pages scrolling via touch pad also isn't working.

**Comment by quinton-ashley** [comment]
Are you using a PC laptop touchpad?

**Comment by qoheniac** [comment]
Firefox 60 for Linux on a Laptop.

E: I will provide links to pages where touch pad scroll isn't working later, as I am currently writing from my phone.

**Comment by quinton-ashley** [comment]
Yeah I assume your PC's touchpad is tied to the native system scrollbar.  This extension removes that native UI element from the window, which disables scrolling so I had to re-implement scrolling via scrollwheel events in jquery.  I don't know if there's a fix for that unfortunately if it's not triggering mousewheel events.  I think in the next version I'll make using the arrow keys to scroll an option.

**Comment by quinton-ashley** [comment]
This has probably been fixed in 2.0.2 thanks to @hensm !  Let me know if it's still not working
