### ISSUE TITLE
Strange scrolling behaviour

### ISSUE THREAD

**Issue by qoheniac** [quinton-ashley/firefox-hide-scrollbars#7]
I observed some strange behaviour while scrolling on some pages. One example is Wikipedia where it is even impossible to read articles while the scrollbars are hidden. If you scroll down there is just a grey block instead of text.

**Comment by quinton-ashley** [comment]
Yes I noticed that too, super weird behavior.  Luckily @hensm has saved the day and 2.0.2 works perfectly on Wikipedia!
