### ISSUE TITLE
Scrolling behaviour on Wikipedia

### ISSUE THREAD

**Issue by qoheniac** [quinton-ashley/firefox-hide-scrollbars#9]
First of all I would like to say how amazed I am of the progress here. I am currently using version 2.0.5 and I can now scroll via touch pad and even arrow keys! But one problem still remains and that's the strange behaviour while scrolling Wikipedia, that is I can only scroll the article's content but not the rest of the page layout which for example makes it impossible for me to access the list of available languages and the top navigation is displayed on top of the article's content. [Here](https://i.imgur.com/pxTPGDh.png) is a screenshot.

**Comment by quinton-ashley** [comment]
@hensm what do you think the issue is here?

**Comment by hensm** [comment]
Fix #10
